name: Azure Deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
        
    steps:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install fastapi
        pip install uvicorn
        pip install httpx
        pip install beautifulsoup4
        pip install openai
    
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "passwordkey"
          replace: ${{ secrets.AZURE_OPENAI_KEY }}
          regex: true
          include: 'back/config.py'
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: 'http://staging-pauline-portfolio.westeurope.azurecontainer.io'
          replace: 'http://pauline-portfolio.westeurope.azurecontainer.io' 
          regex: true
          include: |
            'front/assets/script.js'
            'back/config.py'

    - name: Test backend with pytest
      run: |
        cd back && pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: Azure ACR login
      run: |
        az acr login --name paulineregistreb15

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "passwordkey"
          replace: ${{ secrets.AZURE_OPENAI_KEY }}
          regex: true
          include: 'back/config.py'
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: 'http://staging-pauline-portfolio.westeurope.azurecontainer.io:8000'
          replace: 'http://pauline-portfolio.westeurope.azurecontainer.io:8000' 
          regex: true
          include: 'front/assets/script.js'

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: 'http://staging-pauline-portfolio.westeurope.azurecontainer.io'
          replace: 'http://pauline-portfolio.westeurope.azurecontainer.io' 
          regex: true
          include: 'back/config.py'

    - name: Build and push Docker images
      run: |
        docker build -t back-chat-az back/
        docker build -t front-portfolio-az front/
        docker tag back-chat-az paulineregistreb15.azurecr.io/back-chat-az
        docker tag front-portfolio-az paulineregistreb15.azurecr.io/front-portfolio-az
        docker push paulineregistreb15.azurecr.io/back-chat-az
        docker push paulineregistreb15.azurecr.io/front-portfolio-az
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "password.registry"
        replace: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        regex: false
        include: 'deploy-aci-prod.yaml'
    
    - name: Delete Previous Same Container Instances
      run: az container delete --resource-group pauline-RG-Brief15 --name ProdPaulineContainerGroupPortfolio --yes

    - name: Deploy to Azure Container Instances
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci-prod.yaml