name: Azure Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "passwordkey"
        replace: ${{ secrets.EDENAIKEY }}
        regex: false
        include: 'back/config.py'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install fastapi
        pip install uvicorn
        pip install httpx
        pip install beautifulsoup4
    
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Test backend with pytest
      run: |
        cd back && pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: Azure ACR login
      run: |
        az acr login --name paulineregistreb15

    - name: Build and push Docker images
      run: |
        docker build -t back-chat-az back/
        docker build -t front-portfolio-az front/
        docker tag back-chat-az paulineregistreb15.azurecr.io/back-chat-az-dev
        docker tag front-portfolio-az paulineregistreb15.azurecr.io/front-portfolio-az-dev
        docker push paulineregistreb15.azurecr.io/back-chat-az-dev
        docker push paulineregistreb15.azurecr.io/front-portfolio-az-dev
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "password.registry"
        replace: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        regex: false
        include: 'deploy-aci.yaml'
    
    - name: Delete Previous Same Container Instances
      run: az container delete --resource-group pauline-RG-Brief15 --name paulineContainerGroupPortfolio-dev --yes

    - name: Deploy to Azure Container Instances
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml